sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.4.4"
  - development

env:
  - HAXE_TARGET=cpp
  - HAXE_TARGET=cs
  - HAXE_TARGET=flash
  - HAXE_TARGET=lua
  - HAXE_TARGET=neko
  - HAXE_TARGET=node
  - HAXE_TARGET=php
  - HAXE_TARGET=php7
  - HAXE_TARGET=python
  - HAXE_TARGET=js
  - HAXE_TARGET=java

matrix:
  fast_finish: true
  allow_failures:
    - haxe: development
    - haxe: flash
    - haxe: "3.4.4"
      env: HAXE_TARGET=lua
    - env: HAXE_TARGET=cs
  exclude:
    - haxe: development
      os: osx

# cs fails because of https://github.com/HaxeFoundation/haxe/issues/6533
# lua fails on 3.4.4 with "too many local variables (limit is 200)"

install:
  - haxelib install haxe-doctest
  - haxelib git travix https://github.com/back2dos/travix && pushd . && cd $(haxelib config)travix/git && haxe build-neko.hxml && popd
  - haxelib run travix install

script:
  - haxelib run travix $HAXE_TARGET
