sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.4.5"
  - development

env:
  - HAXE_TARGET=cpp
  - HAXE_TARGET=cs
  - HAXE_TARGET=flash
  - HAXE_TARGET=lua
  - HAXE_TARGET=neko
  - HAXE_TARGET=node
  - HAXE_TARGET=php
  - HAXE_TARGET=php7
  - HAXE_TARGET=python
  - HAXE_TARGET=js
  - HAXE_TARGET=java

matrix:
  fast_finish: true
  allow_failures:
    - haxe: development
    - env: HAXE_TARGET=flash # https://github.com/travis-ci/travis-ci/issues/8481
    - env: HAXE_TARGET=lua   # LUA fails on 3.4.x with "too many local variables (limit is 200)", see https://github.com/HaxeFoundation/haxe/issues/5243
    - env: HAXE_TARGET=cs    # C# fails because of https://github.com/HaxeFoundation/haxe/issues/6533
  exclude:
    - haxe: development
      os: osx

install:
  - haxelib install haxe-doctest
  - haxelib git travix https://github.com/back2dos/travix && pushd . && cd $(haxelib config)travix/git && haxe build-neko.hxml && popd
  - haxelib run travix install

script:
  - haxelib run travix $HAXE_TARGET
